# Generated by Django 3.2.9 on 2021-12-02 11:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MinValueValidator(12)]),
        ),
    ]
