# Generated by Django 3.2.9 on 2021-12-07 08:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20211207_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(max_length=200, unique=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator('^[A-Z][a-z]*', 'Should start with uppercase')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='fname',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator('^[A-Z][a-z]*', 'Should start with uppercase')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='lname',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator('^[A-Z][a-z]*', 'Should start with uppercase')]),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=200, unique=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator('^[A-Z][a-z]*', 'Should start with uppercase')]),
        ),
        migrations.AlterField(
            model_name='supervisior',
            name='fname',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator('^[A-Z][a-z]*', 'Should start with uppercase')]),
        ),
        migrations.AlterField(
            model_name='supervisior',
            name='lname',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator('^[A-Z][a-z]*', 'Should start with uppercase')]),
        ),
    ]
